#!/bin/sh
#=========================================================================================
echo
echo zMole [Nutz.more], version1
echo
echo Setup class path ...
export JAVA_HOME=$JAVA_HOME
echo JAVA_HOME: $JAVA_HOME
export NUTZ_HOME=/home/zozoh/workspace/j2ee/nutz/bin
echo NUTZ_HOME: $NUTZ_HOME
export MOLE_HOME=/home/zozoh/workspace/j2ee/zmole/bin
echo MOLE_HOME: $MOLE_HOME
# Setup classpath
export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/jre/rt.jar
export CLASSPATH=$CLASSPATH:$MOLE_HOME:$NUTZ_HOME
#=========================================================================================
java com.zzh.mole.coder.Coder
