#!/bin/sh
export JAVA_HOME=$JAVA_HOME
export NUTZ_HOME=/home/zozoh/workspace/j2ee/nutz/bin
export ZDOC_HOME=/home/zozoh/workspace/j2ee/zdoc/bin

export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/jre/rt.jar
export CLASSPATH=$CLASSPATH:$ZDOC_HOME:$NUTZ_HOME

java org.nutz.doc.ZDoc $1 $2 $3 $4 $5
